const imageTexts = [
  "Since he was a pizzaiolo he took his long pizza peel and put the stone on it. He brought it home and together with his brothers and sisters they made an oven tray for their new place. ",
  "Always in a rush they forgot where to go and up to this day they are searching for the moss.",
  "They carried their stone carefully to a previously prepared place. There the stone enjoyed great comfort.",
  "He sang a song while walking: my hat my hut i got two stones in my hat if they won't fit in the hut i'll be lost oh my god",
  "She put it in a big empty parking lot, around the corner from where she lived. People from the neighbourhood liked it a lot, and started to bring their own petit stones. Now, every Tuesday afternoon, they move the stones together and have a lot of fun.",
  "We are looking for more information about this stone, please check again later.",
  "This stone became a sculpture in an anthill co-op in Wallonie",
  "Jon Jonson couldn't find his way back to Wisconsin causee each time he wanted to check the way, something else on his phone distracted him.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "Turtle",
  "Fede, the small bird sat on one of the stones and observed everyone else carefully, in case of any misunderstanding between stone takers he used his beautiful calming voice to end the conflict.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "Three balloons took their stone on a trip to the moon.",
  "A small wooden ladder will do as well.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
  "We are looking for more information about this stone, please check again later.",
];
